# Generated by Django 4.1.13 on 2023-11-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('email', models.TextField()),
                ('avatar', models.TextField()),
                ('status', models.CharField(choices=[('ONL', 'Online'), ('OFF', 'Offline'), ('ING', 'Ingame'), ('BUS', 'Busy')], default='OFF', max_length=10)),
                ('admin', models.BooleanField(default=False)),
                ('password', models.CharField(default='abc', max_length=50)),
            ],
        ),
    ]