# Generated by Django 4.1.13 on 2023-12-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('account_creation_method', models.CharField(choices=[('signup', 'Signup Page'), ('intra', 'Intra Login')], default='signup', max_length=10)),
                ('intra_id', models.IntegerField(blank=True, default=None, null=True)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('email', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('status', models.CharField(choices=[('ONL', 'Online'), ('OFF', 'Offline'), ('ING', 'Ingame'), ('BUS', 'Busy')], default='OFF', max_length=10)),
                ('admin', models.BooleanField(default=False)),
                ('password', models.CharField(default='abc', max_length=128)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
