# Generated by Django 4.1.13 on 2023-12-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_creation_method',
            field=models.CharField(choices=[('signup', 'Signup Page'), ('intra', 'Intra Login')], default='signup', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='intra_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
