# Generated by Django 4.2.6 on 2023-11-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ONL', 'Online'), ('OFF', 'Offline'), ('ING', 'Ingame'), ('BUS', 'Busy')], default='O', max_length=10),
        ),
    ]
