# Generated by Django 4.2.6 on 2023-11-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_user_nickname_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ONL', 'Online'), ('OFF', 'Offline'), ('ING', 'Ingame'), ('BUS', 'Busy')], default='ONL', max_length=10),
        ),
    ]
