# Generated by Django 4.2.6 on 2023-11-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ONL', 'Online'), ('OFF', 'Offline'), ('ING', 'Ingame'), ('BUS', 'Busy')], default='OFF', max_length=10),
        ),
    ]
