version: '3.8'

services:
  backend:
    container_name: backend
    restart: on-failure:5
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - media:/usr/src/app/media/
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  postgres:
    container_name: postgres
    image: postgres:alpine3.18
    restart: on-failure:5
    volumes:
      - database-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:7.2.3-alpine3.19
    restart: on-failure:5
    volumes:
      - database-redis:/data
    ports:
      - '6379:6379'
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    restart: on-failure:5
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  database-postgres:
  database-redis:
  media:
