# Generated by Django 4.1.13 on 2023-11-28 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='user_profile.user')),
                ('friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='user_profile.user')),
            ],
            options={
                'verbose_name': 'friend_list',
                'verbose_name_plural': 'friend_list',
            },
        ),
        migrations.AddConstraint(
            model_name='friendlist',
            constraint=models.UniqueConstraint(fields=('friend1', 'friend2'), name='Unique rows friend_list'),
        ),
        migrations.AddConstraint(
            model_name='friendlist',
            constraint=models.CheckConstraint(check=models.Q(('friend1', models.F('friend2')), _negated=True), name='Cannot friend yourself'),
        ),
    ]
