# Generated by Django 4.1.13 on 2023-12-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='timeLastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
