# Generated by Django 4.2.6 on 2023-11-06 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_user_status'),
        ('friend_list', '0002_alter_friendlist_friend1'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='friend2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='user_profile.user'),
        ),
    ]
