# Generated by Django 4.1.13 on 2023-12-17 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend_list', '0002_friendlist_timelastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='last_action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_action_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
