# Generated by Django 4.2.6 on 2023-11-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_list', '0005_alter_friendlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendlist',
            name='unique_rows_friend',
        ),
        migrations.RemoveConstraint(
            model_name='friendlist',
            name='cannot_friend_yourself',
        ),
        migrations.AddConstraint(
            model_name='friendlist',
            constraint=models.UniqueConstraint(fields=('friend1', 'friend2'), name='Unique rows friend_list'),
        ),
        migrations.AddConstraint(
            model_name='friendlist',
            constraint=models.CheckConstraint(check=models.Q(('friend1', models.F('friend2')), _negated=True), name='Cannot friend yourself'),
        ),
    ]
