# Generated by Django 4.2.6 on 2023-11-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocklist',
            options={'verbose_name': 'block_list', 'verbose_name_plural': 'block_list'},
        ),
        migrations.AlterModelTableComment(
            name='blocklist',
            table_comment='Implementation of a blocklist between users on the website',
        ),
        migrations.AddConstraint(
            model_name='blocklist',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked_user'), name='unique_rows'),
        ),
        migrations.AddConstraint(
            model_name='blocklist',
            constraint=models.CheckConstraint(check=models.Q(('blocker', models.F('blocked_user')), _negated=True), name='cannot_block_yourself'),
        ),
    ]
