# Generated by Django 4.2.6 on 2023-11-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_list', '0003_remove_blocklist_unique_rows_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='blocklist',
            name='unique_rows_block_list',
        ),
        migrations.AddConstraint(
            model_name='blocklist',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked_user'), name='Unique rows block list'),
        ),
    ]
