# Generated by Django 4.1.13 on 2024-01-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_invite', '0002_alter_matchinvite_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinvite',
            name='recipient',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matchinvite',
            name='user_inviting',
            field=models.IntegerField(),
        ),
    ]
