# Generated by Django 4.1.13 on 2024-01-06 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_invite', '0003_alter_matchinvite_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinvite',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchinvite',
            name='user_inviting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
