# Generated by Django 4.1.13 on 2023-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookingForMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddleA', models.IntegerField()),
                ('paddleB', models.IntegerField(default=-1)),
            ],
        ),
    ]
