# Generated by Django 4.2.6 on 2023-10-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='bozo',
            field=models.BooleanField(default=False),
        ),
    ]
