# Generated by Django 4.2.6 on 2023-10-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_test_bozo'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='ba',
            field=models.BooleanField(default=False),
        ),
    ]
