# Generated by Django 4.2.6 on 2023-11-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamenthistory',
            name='time_of_match',
            field=models.TimeField(auto_now=True),
        ),
    ]
