# Generated by Django 4.2.6 on 2023-11-07 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_user_status'),
        ('tournament_history', '0004_alter_tournamenthistory_time_of_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamenthistory',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loserTournament', to='user_profile.user'),
        ),
        migrations.AlterField(
            model_name='tournamenthistory',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winnerTournament', to='user_profile.user'),
        ),
    ]
