# Generated by Django 4.2.6 on 2023-11-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='date_of_match',
            field=models.TimeField(default='20:00'),
        ),
    ]
