# Generated by Django 4.2.6 on 2023-11-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0002_alter_matchhistory_date_of_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='date_of_match',
            field=models.TimeField(),
        ),
    ]
