# Generated by Django 4.2.6 on 2023-11-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0004_alter_matchhistory_date_of_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchhistory',
            options={'verbose_name': 'match_history', 'verbose_name_plural': "match_history's"},
        ),
        migrations.AlterModelTableComment(
            name='matchhistory',
            table_comment='Implementation of a match_history table for pong',
        ),
        migrations.AddConstraint(
            model_name='matchhistory',
            constraint=models.UniqueConstraint(fields=('winner', 'loser'), name='unique_rows_match_history'),
        ),
        migrations.AddConstraint(
            model_name='matchhistory',
            constraint=models.CheckConstraint(check=models.Q(('winner', models.F('loser')), _negated=True), name='winner and loser were the same'),
        ),
    ]
