# Generated by Django 4.2.6 on 2023-11-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0005_alter_matchhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchhistory',
            name='unique_rows_match_history',
        ),
        migrations.RemoveConstraint(
            model_name='matchhistory',
            name='winner and loser were the same',
        ),
        migrations.AddConstraint(
            model_name='matchhistory',
            constraint=models.CheckConstraint(check=models.Q(('winner', models.F('loser')), _negated=True), name='winner and loser are the same user'),
        ),
    ]
